name: Build, Cache, and Deploy

on:
  push:
    branches:
      - main

jobs:
  cache_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add version to version.txt
        run: echo "v0.0.1" > version.txt

      - name: Create version artifact
        run: |
          mkdir -p artifacts
          cp version.txt artifacts/
        # Create an artifact containing the version.txt file
        # This artifact can be used in subsequent steps
        # to retrieve the version string

      - name: Build and deploy
        run: |
          mkdir -p public
          cp index.html public/
          # You can add additional build or copying steps here

        # Store the version artifact
      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: artifacts

      - name: Download version artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact
          path: artifacts

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./public
