name: Build, Cache, and Deploy

on:
  push:
    branches:
      - main

jobs:
  cache_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache version string
        uses: actions/cache@v2
        with:
          path: version
          key: ${{ runner.os }}-version-${{ hashFiles('version') }}
          restore-keys: |
            ${{ runner.os }}-version-

      - name: Create version artifact
        run: echo "v0.0.1" > version.txt
        # Create an artifact containing the version.txt file
        # This artifact can be used in subsequent steps
        # to retrieve the version string

      - name: Build and deploy
        run: |
          mkdir -p public
          cp index.html public/
          # You can add additional build or copying steps here

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./public

      # Store the version.txt artifact
      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version-artifact
          path: version.txt
