name: Build, Cache, and Deploy

on:
  push:
    branches:
      - main

jobs:
  cache_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        if: success()
        uses: actions/checkout@v2

      - name: Add version to version.txt
        if: success()
        run: echo "v0.0.64" > version.txt

      - name: Create version artifact
        if: success()
        id: create-artifact
        run: |
          mkdir -p site
          cp version.txt site/
        # Create an artifact containing the version.txt file
        # This artifact can be used in subsequent steps
        # to retrieve the version string

      - name: Build and deploy
        run: |
          cp index.html site/

      - name: Upload version artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: site-artifact
          path: site

      - name: Download version artifact
        if: success() # This step depends on the success of the previous step
        uses: actions/download-artifact@v2
        with:
          name: site-artifact
          path: site

      - name: Deploy 🚀
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: 'site'
